name: telegram messagetestco
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -629136383
          token: 5344445377:AAHF6t34HHjvC2zTMGgj-OLgxfkTs93uGf4
          message: |
            ${{ github.actor }} hizo commit:
            "Commit message: ${{ github.event.commits[0].message }}"
                        
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref }}
            
            https://github.com/${{ github.repository }}/commit/${{github.sha}}
